const express = require("express");
const router = express.Router();

const ExpenseController = require("../controllers/expense")

router.get('/directdebit', ExpenseController.DirectDebit)
router.post('/directdebit', ExpenseController.UpdateDebit)
router.get('/:month/:id', ExpenseController.Update)
router.get('/january', ExpenseController.January)
router.post('/january', ExpenseController.AddToJanuary)
router.post('/january/update/:id', ExpenseController.UpdateJan)
router.get('/february', ExpenseController.February)
router.post('/february', ExpenseController.AddToFebruary)
router.post('/february/update/:id', ExpenseController.UpdateFeb)
router.get('/march', ExpenseController.March)
router.post('/march', ExpenseController.AddToMarch)
router.post('/march/update/:id', ExpenseController.UpdateMar)
router.get('/april', ExpenseController.April)
router.post('/april', ExpenseController.AddToApril)
router.post('/april/update/:id', ExpenseController.UpdateApr)
router.get('/may', ExpenseController.May)
router.post('/may', ExpenseController.AddToMay)
router.post('/may/update/:id', ExpenseController.UpdateMay)
router.get('/june', ExpenseController.June)
router.post('/june', ExpenseController.AddToJune)
router.post('/june/update/:id', ExpenseController.UpdateJune)
router.get('/july', ExpenseController.July)
router.post('/july', ExpenseController.AddToJuly)
router.post('/july/update/:id', ExpenseController.UpdateJuly)
router.get('/august', ExpenseController.August)
router.post('/august', ExpenseController.AddToAugust)
router.post('/august/update/:id', ExpenseController.UpdateAug)
router.get('/september', ExpenseController.September)
router.post('/september', ExpenseController.AddToSeptember)
router.post('/september/update/:id', ExpenseController.UpdateSept)
router.get('/october', ExpenseController.October)
router.post('/october', ExpenseController.AddToOctober)
router.post('/october/update/:id', ExpenseController.UpdateOct)
router.get('/november', ExpenseController.November)
router.post('/november', ExpenseController.AddToNovember)
router.post('/november/update/:id', ExpenseController.UpdateNov)
router.get('/december', ExpenseController.December)
router.post('/december', ExpenseController.AddToDecember)
router.post('/december/update/:id', ExpenseController.UpdateDec)
module.exports = router;
